
dist: focal
os: linux
cache: false
git:
  depth: false 
  
before_script:
  - chmod +x script.sh
  
script:
  - |
    #set -e
    ./script.sh

after_success:
  - echo "pass"
  
after_failure:
  - echo "fail"
