arch: ppc64le

env:
  global: 
    - PHASES="1, 3, 5"
  
script: echo $PHASES

jobs:
  include:
    - stage: Phase 3
      if: 1 IN (env(PHASES))
    - stage: Phase 5
      if: env(PHASES) =~ /[5]/
    - stage: Phase 2
      if: 2 IN (env(PHASES))


