arch: ppc64le

env:
  global: PHASES="1 2 3 4"
  
jobs:
  include:
    - stage: Phase 1
      if: "1" in env(PHASES)
      script: echo $PHASE
    - stage: Phase 3
      if: "3" in env(PHASES)
      script: echo $PHASE
    - stage: Phase 5
      if: "5" in env(PHASES)
      script: echo $PHASE
