language: go
dist: focal
os: linux

jobs:
  include:
   - &unit-test
     stage: run unit test
     script:
       - echo "run unit test"
     name: run unit test on amd64
     arch: amd64
   - <<: *unit-test
     name: run unit test on ppc64le
     arch: ppc64le
     script: bash -c "exit 1"
   - <<: *unit-test
     name: run unit test on s390x
     arch: s390x
     
   - &test
     stage: run unit test
     script:
       - echo "run unit test"
     name: run unit test on amd64
     arch: amd64
   - <<: *test
     name: run unit test on ppc64le
     arch: ppc64le
     script: bash -c "exit 1"
   - <<: *test
     name: run unit test on s390x
     arch: s390x

  allow_failures:
  - arch: ppc64le
    name: run unit test on ppc64le


  
