language: go

go:
- "1.15"

os: linux
dist: focal

git:
  depth: false

services:
  - docker

env:  
   global:
   - TAG=next
   - TRAVIS_TAG=travis
   - REGISTRY=quay.io
   - ORGANIZATION=prabhav
   - IMAGE=che-machine-exec

jobs:
  include:
   - &docker-build-pr
     stage: PR Check
     if: type = pull_request
     name: Check docker build on amd64
     install: skip
     script: sleep 1m
     arch: amd64
   - <<: *docker-build-pr
     name: Check docker build on ppc64le
     arch: ppc64le
   - <<: *docker-build-pr
     name: check docker build PR on s390x
     arch: s390x
   - <<: *docker-build-pr
     name: check docker build PR on arm64
     arch: arm64

   - &unit-test
     name: Run unit tests on amd64
     if: type = pull_request
     script: sleep 1m
     arch: amd64
   - <<: *unit-test
     name: Run unit tests on arm64
     arch: arm64
   - <<: *unit-test
     name: Run unit tests on ppc64le
     arch: ppc64le
   - <<: *unit-test
     name: Run unit tests on s390x
     arch: s390x
     script:
     - sleep 3m
     - bash -c "exit 1"

   - &next-build
     stage: Build and push both short SHA tag and next tag
     name: Build image on amd64
     if: type = push
     script: sleep 1m
     arch: amd64
   - <<: *next-build
     name: Build image on arm64
     arch: arm64
   - <<: *next-build
     name: Build image on ppc64le
     arch: ppc64le
   - <<: *next-build
     name: Build image on s390x
     arch: s390x
   
  fast_finish: true
  allow_failures:
   - if: type = pull_request
     arch: ppc64le
   - if: type = pull_request
     arch: arm64
